apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-cicd-example-deployment
  labels:
    app: nextjs-cicd-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-cicd-example
  template:
    metadata:
      labels:
        app: nextjs-cicd-example
    spec:
      containers:
        - name: nextjs-cicd-example
          image: kiss0104040/nextjs-cicd-example:96ccefcf01ecb95ed5704e31a197481d24da710e
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-cicd-example-service
spec:
  selector:
    app: nextjs-cicd-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
