apiVersion: apps/v1
kind: Deployment
metadta:
  name: nextjs-cicd-example-deployment
  labels:
    app: nextjs-cicd-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-cicd-example
  template:
    metadata:
      labels:
        app: nextjs-cicd-example
    spec:
      containers:
        - name: nextjs-cicd-example
          image: your_docker_username/nextjs-cicd-example:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
---
apiVersion: 1
kind: Service
metadta:
  name: nextjs-cicd-example-service
spec:
  selector:
    app: nextjs-cicd-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
